import { prisma } from '../src/lib/db';

async function seedSettings() {
  await prisma.brandingSetting.upsert({
    where: { id: 'cosko_branding_config' },
    create: {
      id: 'cosko_branding_config',
      appName: 'COSKO Enterprise',
      tagline: 'Multi-Store Enterprise Retail & POS System',
      supportEmail: 'support@cosko.com',
      supportPhone: '+91 80 4000 8800',
      businessName: 'COSKO Retail Enterprise Private Limited',
      businessAddress: '100 Feet Ring Road, Indiranagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560038',
      baseCurrency: 'INR (₹)',
    },
    update: {
      appName: 'COSKO Enterprise',
      tagline: 'Multi-Store Enterprise Retail & POS System',
      supportEmail: 'support@cosko.com',
      supportPhone: '+91 80 4000 8800',
      businessName: 'COSKO Retail Enterprise Private Limited',
      businessAddress: '100 Feet Ring Road, Indiranagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560038',
      baseCurrency: 'INR (₹)',
    },
  });

  await (prisma as any).systemSettings.upsert({
    where: { id: 'cosko_system_config' },
    create: {
      id: 'cosko_system_config',
      gstin: '29AABCU9603R1ZM',
      legalBusinessName: 'COSKO Retail Enterprise Private Limited',
      tradeName: 'COSKO Stores',
      gstState: 'Karnataka',
      gstStateCode: '29',
      gstRegistrationType: 'Regular',
      defaultTaxRate: 18.0,
      hsnMandatory: true,
      enableReverseCharge: false,
      gstBusinessAddress: '100 Feet Ring Road, Indiranagar, Bengaluru, Karnataka - 560038',
      invoiceHeader: 'COSKO Retail Enterprise',
      invoiceFooter: 'Thank you for shopping with us! Goods once sold cannot be returned without original receipt.',
      invoiceTerms: '1. Standard 12-month warranty on manufacturing defects.\n2. Retain this invoice for warranty & service support.\n3. Physical and liquid damage are excluded.',
      invoiceAccentColor: 'primary',
      watermarkOpacity: 5,
      showStoreAddress: true,
      showPaymentQr: true,
      paymentUpiId: 'cosko@icici',
      paymentBankDetails: 'HDFC Bank · A/C 50200012345678 · IFSC HDFC0001234',
      sessionTimeoutMins: 30,
      maxLoginAttempts: 5,
      enforcePasswordPolicy: true,
      sensitiveActionConfirm: true,
      lowStockAlerts: true,
      lowStockThreshold: 5,
      overduePaymentAlerts: true,
      overdueThresholdDays: 30,
      dailySalesDigest: false,
      securityEventAlerts: true,
      alertRecipientEmails: 'alerts@cosko.com, finance@cosko.com',
    },
    update: {
      gstin: '29AABCU9603R1ZM',
      legalBusinessName: 'COSKO Retail Enterprise Private Limited',
      tradeName: 'COSKO Stores',
      gstState: 'Karnataka',
      gstStateCode: '29',
      gstRegistrationType: 'Regular',
      defaultTaxRate: 18.0,
      hsnMandatory: true,
      enableReverseCharge: false,
      gstBusinessAddress: '100 Feet Ring Road, Indiranagar, Bengaluru, Karnataka - 560038',
      invoiceHeader: 'COSKO Retail Enterprise',
      invoiceFooter: 'Thank you for shopping with us! Goods once sold cannot be returned without original receipt.',
      invoiceTerms: '1. Standard 12-month warranty on manufacturing defects.\n2. Retain this invoice for warranty & service support.\n3. Physical and liquid damage are excluded.',
      invoiceAccentColor: 'primary',
      watermarkOpacity: 5,
      showStoreAddress: true,
      showPaymentQr: true,
      paymentUpiId: 'cosko@icici',
      paymentBankDetails: 'HDFC Bank · A/C 50200012345678 · IFSC HDFC0001234',
      sessionTimeoutMins: 30,
      maxLoginAttempts: 5,
      enforcePasswordPolicy: true,
      sensitiveActionConfirm: true,
      lowStockAlerts: true,
      lowStockThreshold: 5,
      overduePaymentAlerts: true,
      overdueThresholdDays: 30,
      dailySalesDigest: false,
      securityEventAlerts: true,
      alertRecipientEmails: 'alerts@cosko.com, finance@cosko.com',
    },
  });

  console.log('✅ Default settings successfully seeded into MySQL!');
}

seedSettings()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
